# netlify.toml

[build]
  functions = "netlify/functions"

# Chuyển hướng tất cả các request đến function 'api'
# Điều này cho phép bạn gọi /proxy thay vì /api/proxy
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
